apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: entrepot-azurefile-csi
provisioner: file.csi.azure.com
parameters:
  skuName: Standard_LRS  # par défaut
  storageAccount: entrepot4aks
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=0
  - gid=0
  - mfsymlinks
  - cache=strict
  - nosharesock
  - actimeo=30
  - nobrl