apiVersion: apps/v1
kind: Deployment
metadata:
  name: boutique
  labels:
    app: boutique
spec:
  replicas: 2
  selector:
    matchLabels:
      app: boutique
  template:
    metadata:
      labels:
        app: boutique
    spec:
      containers:
        - name: serveurweb
          image: nginx:alpine
          volumeMounts:
            - name: fichierswebstatiques
              mountPath: /usr/share/nginx/html
      volumes:
        - name: fichierswebstatiques
          persistentVolumeClaim:
            claimName: demande-pv-boutique