apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: thomas.deoliveira2024@campus-eni.fr
    privateKeySecretRef:
      name: clef-letsencrypt-prod
    solvers:
      - http01:
          ingress:
            ingressClassName: nginx
